/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.validation;

import de.htwg.mdsd.playmorphiamodelling.validation.AbstractPlayMorphiaModellingValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PlayMorphiaModellingValidator extends AbstractPlayMorphiaModellingValidator {
}
