/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.ui;

import de.htwg.mdsd.playmorphiamodelling.ui.AbstractPlayMorphiaModellingUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PlayMorphiaModellingUiModule extends AbstractPlayMorphiaModellingUiModule {
  public PlayMorphiaModellingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
