/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.playMorphiaModelling;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.mdsd.playmorphiamodelling.playMorphiaModelling.PlayMorphiaModellingPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
