/*
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.tests

import com.google.inject.Inject
import de.htwg.mdsd.playmorphiamodelling.playMorphiaModelling.Domainmodel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PlayMorphiaModellingInjectorProvider)
class PlayMorphiaModellingParsingTest{

	@Inject
	ParseHelper<Domainmodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
