/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.playMorphiaModelling.impl;

import de.htwg.mdsd.playmorphiamodelling.playMorphiaModelling.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PlayMorphiaModellingFactoryImpl extends EFactoryImpl implements PlayMorphiaModellingFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PlayMorphiaModellingFactory init()
  {
    try
    {
      PlayMorphiaModellingFactory thePlayMorphiaModellingFactory = (PlayMorphiaModellingFactory)EPackage.Registry.INSTANCE.getEFactory(PlayMorphiaModellingPackage.eNS_URI);
      if (thePlayMorphiaModellingFactory != null)
      {
        return thePlayMorphiaModellingFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PlayMorphiaModellingFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PlayMorphiaModellingFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PlayMorphiaModellingPackage.DOMAINMODEL: return createDomainmodel();
      case PlayMorphiaModellingPackage.PACKAGE_DECLARATION: return createPackageDeclaration();
      case PlayMorphiaModellingPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case PlayMorphiaModellingPackage.MORPHIA_MODEL: return createMorphiaModel();
      case PlayMorphiaModellingPackage.ATTRIBUTE: return createAttribute();
      case PlayMorphiaModellingPackage.TYPE: return createType();
      case PlayMorphiaModellingPackage.DATA_TYPE: return createDataType();
      case PlayMorphiaModellingPackage.IMPORT: return createImport();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Domainmodel createDomainmodel()
  {
    DomainmodelImpl domainmodel = new DomainmodelImpl();
    return domainmodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageDeclaration createPackageDeclaration()
  {
    PackageDeclarationImpl packageDeclaration = new PackageDeclarationImpl();
    return packageDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MorphiaModel createMorphiaModel()
  {
    MorphiaModelImpl morphiaModel = new MorphiaModelImpl();
    return morphiaModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType createDataType()
  {
    DataTypeImpl dataType = new DataTypeImpl();
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PlayMorphiaModellingPackage getPlayMorphiaModellingPackage()
  {
    return (PlayMorphiaModellingPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PlayMorphiaModellingPackage getPackage()
  {
    return PlayMorphiaModellingPackage.eINSTANCE;
  }

} //PlayMorphiaModellingFactoryImpl
