/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.ui.contentassist;

import de.htwg.mdsd.playmorphiamodelling.ui.contentassist.AbstractPlayMorphiaModellingProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PlayMorphiaModellingProposalProvider extends AbstractPlayMorphiaModellingProposalProvider {
}
