/*
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PlayMorphiaModellingStandaloneSetup extends PlayMorphiaModellingStandaloneSetupGenerated {

	def static void doSetup() {
		new PlayMorphiaModellingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
