/*
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.ui;

import com.google.inject.Injector;
import de.htwg.mdsd.playmorphiamdoelling.ui.internal.PlaymorphiamdoellingActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlayMorphiaModellingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlaymorphiamdoellingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlaymorphiamdoellingActivator.getInstance().getInjector(PlaymorphiamdoellingActivator.DE_HTWG_MDSD_PLAYMORPHIAMODELLING_PLAYMORPHIAMODELLING);
	}
	
}
