/*
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPlayMorphiaModellingScopeProvider extends DelegatingScopeProvider {
}
