/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling;

import de.htwg.mdsd.playmorphiamodelling.AbstractPlayMorphiaModellingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlayMorphiaModellingRuntimeModule extends AbstractPlayMorphiaModellingRuntimeModule {
}
