/**
 * generated by Xtext 2.10.0
 */
package de.htwg.mdsd.playmorphiamodelling;

import de.htwg.mdsd.playmorphiamodelling.PlayMorphiaModellingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlayMorphiaModellingStandaloneSetup extends PlayMorphiaModellingStandaloneSetupGenerated {
  public static void doSetup() {
    PlayMorphiaModellingStandaloneSetup _playMorphiaModellingStandaloneSetup = new PlayMorphiaModellingStandaloneSetup();
    _playMorphiaModellingStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
